config/routes.rb
Rails.application.routes.draw do
  root 'tweets#index'
  
  resources :tweets, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
  end
  
  def create
    Tweet.create(tweet_params)
  end
  
  private
  def tweet_params
    params.permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nekotter2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/create.html.erb
<p>投稿が完了しました！</p>
<%= link_to "トップページに戻る", root_path %>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="style.css">
    <title>ねこったー</title>
  </head>
  <body>
    <header>
      <h1>ねこったー</h1>
      <div class="new_page">
        <%= link_to "投稿する", new_tweet_path %>
      </div>
    </header>
    <div class="contents">
      <% @tweets.each do |tweet| %>
        <div class="message clearfix">
          <%= image_tag 'cat1.png' %>
          <div class="message_box">
            <p class="user_name">
              野良猫1号
              <!-- <span class="time">・8月13日</span> -->
            <p>
            <p class="text">
              <%= tweet.text %>
            </p>
          </div>
        </div>
      <% end %>
      <div class="message clearfix">
        <%= image_tag "cat1.png" %>
        <div class="message_box">
          <p class="user_name">たま
            <!-- <span class="time">・8月13日</span> -->
          <p>
          <p class="text">
            家宝は寝て待てにゃー。急がば回れにゃー。蓼食う虫も好き好きにゃー。一念岩をも通すにゃー。千石取れば万石羨むにゃー。
          <p>
        </div>
      </div>
     
    </div>
  </body>
</html>

app/views/tweets/new.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link rel="stylesheet" type="text/css" href="style.css">
    <title>ねこったー</title>
  </head>
  <body>
    <header>
      <h1>ねこったー</h1>
    </header>
    <div class="contents">
      <h2>投稿する</h2>
      <%= form_tag('/tweets', method: :post, class: "clearfix") do %>
        <img src="/assets/cat1.png">
        <div class="input-box">
          <textarea rows="4" cols="40" name="text"></textarea>
        </div>
        <div class="button-box">
          <input type="submit" class="submit-button">
        </div>
      <% end %>
    </div>
  </body>
</html>